//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyDescription("CLI TimeZone Info for .NET 6 in FSharp. Ported from https://github.com/merschformann/gotz")]
[assembly: AssemblyProduct("fitz")]
[assembly: AssemblyVersion("0.0.1")]
[assembly: AssemblyFileVersion("0.1.0+6")]
[assembly: AssemblyInformationalVersion("0.1.0+6")]

