#r @"C:\Users\endow\.nuget\packages\argu\6.1.1\lib\netstandard2.0\Argu.dll"
#r @"C:\Users\endow\.nuget\packages\fsharp.json\0.4.1\lib\netstandard2.0\FSharp.Json.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\Microsoft.CSharp.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\Microsoft.VisualBasic.Core.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\Microsoft.VisualBasic.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\Microsoft.Win32.Primitives.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\Microsoft.Win32.Registry.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.AppContext.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Buffers.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Collections.Concurrent.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Collections.Immutable.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Collections.NonGeneric.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Collections.Specialized.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Collections.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.ComponentModel.Annotations.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.ComponentModel.DataAnnotations.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.ComponentModel.EventBasedAsync.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.ComponentModel.Primitives.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.ComponentModel.TypeConverter.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.ComponentModel.dll"
#r @"C:\Users\endow\.nuget\packages\system.configuration.configurationmanager\4.4.0\ref\netstandard2.0\System.Configuration.ConfigurationManager.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Configuration.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Console.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Core.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Data.Common.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Data.DataSetExtensions.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Data.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Diagnostics.Contracts.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Diagnostics.Debug.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Diagnostics.DiagnosticSource.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Diagnostics.FileVersionInfo.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Diagnostics.Process.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Diagnostics.StackTrace.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Diagnostics.TextWriterTraceListener.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Diagnostics.Tools.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Diagnostics.TraceSource.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Diagnostics.Tracing.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Drawing.Primitives.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Drawing.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Dynamic.Runtime.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Formats.Asn1.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Globalization.Calendars.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Globalization.Extensions.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Globalization.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.IO.Compression.Brotli.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.IO.Compression.FileSystem.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.IO.Compression.ZipFile.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.IO.Compression.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.IO.FileSystem.AccessControl.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.IO.FileSystem.DriveInfo.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.IO.FileSystem.Primitives.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.IO.FileSystem.Watcher.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.IO.FileSystem.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.IO.IsolatedStorage.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.IO.MemoryMappedFiles.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.IO.Pipes.AccessControl.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.IO.Pipes.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.IO.UnmanagedMemoryStream.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.IO.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Linq.Expressions.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Linq.Parallel.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Linq.Queryable.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Linq.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Memory.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.Http.Json.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.Http.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.HttpListener.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.Mail.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.NameResolution.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.NetworkInformation.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.Ping.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.Primitives.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.Requests.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.Security.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.ServicePoint.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.Sockets.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.WebClient.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.WebHeaderCollection.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.WebProxy.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.WebSockets.Client.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.WebSockets.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Net.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Numerics.Vectors.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Numerics.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.ObjectModel.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Reflection.DispatchProxy.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Reflection.Emit.ILGeneration.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Reflection.Emit.Lightweight.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Reflection.Emit.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Reflection.Extensions.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Reflection.Metadata.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Reflection.Primitives.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Reflection.TypeExtensions.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Reflection.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Resources.Reader.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Resources.ResourceManager.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Resources.Writer.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Runtime.CompilerServices.Unsafe.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Runtime.CompilerServices.VisualC.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Runtime.Extensions.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Runtime.Handles.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Runtime.InteropServices.RuntimeInformation.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Runtime.InteropServices.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Runtime.Intrinsics.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Runtime.Loader.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Runtime.Numerics.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Runtime.Serialization.Formatters.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Runtime.Serialization.Json.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Runtime.Serialization.Primitives.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Runtime.Serialization.Xml.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Runtime.Serialization.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Runtime.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Security.AccessControl.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Security.Claims.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Security.Cryptography.Algorithms.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Security.Cryptography.Cng.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Security.Cryptography.Csp.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Security.Cryptography.Encoding.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Security.Cryptography.OpenSsl.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Security.Cryptography.Primitives.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Security.Cryptography.X509Certificates.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Security.Principal.Windows.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Security.Principal.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Security.SecureString.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Security.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.ServiceModel.Web.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.ServiceProcess.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Text.Encoding.CodePages.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Text.Encoding.Extensions.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Text.Encoding.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Text.Encodings.Web.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Text.Json.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Text.RegularExpressions.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Threading.Channels.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Threading.Overlapped.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Threading.Tasks.Dataflow.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Threading.Tasks.Extensions.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Threading.Tasks.Parallel.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Threading.Tasks.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Threading.Thread.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Threading.ThreadPool.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Threading.Timer.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Threading.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Transactions.Local.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Transactions.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.ValueTuple.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Web.HttpUtility.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Web.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Windows.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Xml.Linq.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Xml.ReaderWriter.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Xml.Serialization.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Xml.XDocument.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Xml.XPath.XDocument.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Xml.XPath.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Xml.XmlDocument.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Xml.XmlSerializer.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.Xml.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\System.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\WindowsBase.dll"
#r @"C:\Users\endow\scoop\apps\dotnet-sdk\current\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0\netstandard.dll"
#load @"c:\Users\endow\Documents\fitz\Literal.fs"
#load @"c:\Users\endow\Documents\fitz\Type.fs"
#load @"c:\Users\endow\Documents\fitz\Base.fs"
#load @"c:\Users\endow\Documents\fitz\Program.fs"

open System
open fitz

let config, _ = Configuration.load
let colors : Configuration.PlotColors = 
    {
        ColorMorning = "darkcyan"
        ColorDay = "cyan"
        ColorEvening = "darkCyan"
        ColorNight = "blue"
        Foreground = ""
        Background = ""
    } 

let style = { config.Style with Colorize = true; Colors = colors } 

let timeCheck = DateTime.Parse("11:00")

Plot.plotTime { config with Style = style; Tics = true; Hours12 = true} DateTime.Now
Plot.plotTime { config with Style = style; Tics = true; Hours12 = false} DateTime.Now
Plot.plotTime { config with Style = style; Tics = true; Hours12 = false} timeCheck 

Fitz.main [| "--tics"; "--colorize" |] 
